<?php

namespace AppBundle\Repository;


/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
        public function findLikeSearch($search, $type)
        {
             $qb = $this->getEntityManager()->createQueryBuilder();
             if($type)
             {
                $qb->select('u')
                    ->from('AppBundle:Customer', 'u')
                    ->where('u.'.$type.' LIKE :search')
                    ->setParameter('search','%'.$search.'%');
             }
             else
             {
                 $qb->select('u')
                    ->from('AppBundle:Customer', 'u')
                    ->where('u.name LIKE :search')
                    ->setParameter('search','%'.$search.'%');  
             }
             return $qb->getQuery()->getResult();   
        }
        
        public function EnumerateCustomers($user)
        {
   
            
        }
}
