<?php

namespace AppBundle\Repository;

/**
 * PermisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisionRepository extends \Doctrine\ORM\EntityRepository
{
}
